on:
  workflow_dispatch:

  schedule:
    - cron: "0 0 1 * *"

jobs:
  build_container:
    runs-on: ubuntu-latest
    name: Build a new container
    steps:
      - uses: actions/checkout@v4
      - id: builder
        uses: Zoobdude/caddy-docker-builder@v1
        with:
          modules: |
            github.com/caddy-dns/cloudflare
            github.com/porech/caddy-maxmind-geolocation
            github.com/greenpau/caddy-security@v1.1.29
          docker-username: "zoobdude"
          docker-password: ${{ secrets.DOCKERHUB_TOKEN }}
          tags: "zoobdude/caddy"
          platforms: linux/amd64,linux/arm64,linux/arm/v7
